{% set name = "ipyvizzu-story" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4aa5bcec78a874b48e80fc38a22a5c27bd4c66535e1aefe2570be0cdf4b195f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pdm-backend
  run:
    - python >=3.6
    - ipyvizzu

test:
  imports:
    - ipyvizzustory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ipyvizzu-story.vizzuhq.com
  summary: Build, present and share animated data stories in Jupyter Notebook and similar environments.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Build, present and share animated data stories in Jupyter Notebook and similar environments.

    [![gif][_gif]](https://ipyvizzu-story.vizzuhq.com)

    [_gif]: https://ipyvizzu-story.vizzuhq.com/latest/assets/ipyvizzu-story.gif

    PyPI: [https://badge.fury.io/py/ipyvizzu-story](https://badge.fury.io/py/ipyvizzu-story)

  doc_url: https://ipyvizzu-story.vizzuhq.com
  dev_url: https://github.com/vizzuhq/ipyvizzu-story

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - veghdev
