{% set name = "ipyvizzu-story" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyvizzu-story-{{ version }}.tar.gz
  sha256: f56e92573e14812ca8280bec4e6615f69f1f66eea8f6b6306dff02fe811c00f2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ipyvizzu

test:
  imports:
    - ipyvizzustory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vizzuhq/ipyvizzu-story
  summary: Create and present animated data stories within data science notebooks.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Create and present animated data stories within data science notebooks.

    [![gif][_gif]](https://vizzuhq.github.io/ipyvizzu-story)

    [_gif]: https://github.com/vizzuhq/ipyvizzu-story/raw/main/docs/examples/demo/ipyvizzu-story_example.gif

    PyPI: [https://badge.fury.io/py/ipyvizzu-story](https://badge.fury.io/py/ipyvizzu-story)

  doc_url: https://vizzuhq.github.io/ipyvizzu-story
  dev_url: https://github.com/vizzuhq/ipyvizzu-story

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - veghdev
