{% set name = "ipyvizzu-story" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyvizzu-story-{{ version }}.tar.gz
  sha256: 8df2e68e9242684ee07ecb7b8fa4d759e66d5a6f964ce799ebbcb43221469e27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ipyvizzu

test:
  imports:
    - ipyvizzustory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ipyvizzu-story.vizzuhq.com
  summary: Build, present and share animated data stories in Jupyter Notebook and similar environments.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Build, present and share animated data stories in Jupyter Notebook and similar environments.

    [![gif][_gif]](https://ipyvizzu-story.vizzuhq.com)

    [_gif]: https://ipyvizzu-story.vizzuhq.com/latest/assets/ipyvizzu-story.gif

    PyPI: [https://badge.fury.io/py/ipyvizzu-story](https://badge.fury.io/py/ipyvizzu-story)

  doc_url: https://ipyvizzu-story.vizzuhq.com
  dev_url: https://github.com/vizzuhq/ipyvizzu-story

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - veghdev
